# -*- coding: utf-8 -*-
"""Manthan-facing context for the Computation-screen review page.

Two answerable streams:
  CELLS         — the 30 cells the Computation screen renders, in render order. Each is annotated
                  with today's logic in plain words + the three questions Manthan answers per cell:
                  correct? · where should it come from? · read-only or editable?
  MAP_DECISIONS — the auto-capture mapping proposal (the 28 Manthan questions from the
                  return-to-computation mapping table), grouped.

Sources, kept as muted footnotes (Manthan can ignore them; engineers can't):
  - Cell logic + file:line  →  documents/computation-screen-replica-2026-08-16.md (+ .csv)
  - Mapping proposal        →  documents/return-to-computation-mapping-table-2026-08-16.md
Build of record cited by both source docs: origin/main (COI engine + feed maps byte-identical across
the small UI gap). Plain language throughout; engineering terms explained once in the glossary.
Written by the computation-review session, 2026-08-16.
"""

# The three questions asked on EVERY cell (the per-cell "YOUR CALL").
CELL_Q_CORRECT = ["Correct — logic is right", "Wrong — logic is off (say how below)",
                  "Should come from elsewhere (fill the box)"]
CELL_Q_MODE = ["Read-only (owned upstream)", "Editable — pre-filled from a schedule",
               "Editable — blank (typed here)"]

# ── The 30 cells, in the exact order the screen renders (replica section B) ───────────────────────
# band: one of income / addbacks / deductions / tax / other  (drives the section grouping + crop)
# variant: 'both' or 'FZ'   ·   mode_today: short tag shown as the current build's treatment
CELLS = [
 # BAND 1 — Income & accounting base
 dict(n=1, id='C5', code='C5', label='Accounting Income of the Taxable Person', band='income', variant='both',
   mode_today='Read-only — computed', klass='A',
   logic="The mapped financial-statement net profit, brought in as the starting accounting income and rounded once to whole AED. The screen does no maths of its own — the engine re-runs the ladder.",
   feeds_in="Financial-statement mapping — the rolled Section-C net profit (C!H23 → COI!C5).",
   feeds_out="C24 (taxable income before loss relief). Article 20(1).",
   open="",
   src="ladder.ts:556-557 · coi-surface.ts:94,440-447"),
 dict(n=2, id='C6', code='C6', label='Unrealised gains / (losses)', band='income', variant='both',
   mode_today='Read-only — from schedule', klass='',
   logic="A signed total from the Unrealised Gain/Loss schedule: gains minus losses. Read-only here; you change it by editing that schedule (the 'Reclassify upstream' link).",
   feeds_in="Return schedule #6 (Unrealised Gain/Loss — income recognised / loss recognised).",
   feeds_out="C24. Article 20(2)(a).",
   open="Signs flagged 'ratify at staging' — the plus/minus convention wants a passive confirm.",
   src="coi-ladder-feeds.ts:111-116,219-221"),
 dict(n=3, id='C8', code='C8', label='Exempt income — dividends & profit distributions', band='income', variant='both',
   mode_today='Read-only — from schedule', klass='',
   logic="Minus the total of profit distributions (exempt income reduces income, so it is passed as a negative). Owned by the UAE Dividend schedule.",
   feeds_in="S060 UAE Dividend schedule (#11).",
   feeds_out="C24. Article 20(2)(b).",
   open="FILED note: an old prototype said a Section-D 'No' answer would hide this surface AND drop the feed; the build does NOT drop retained dividend rows while hidden. Worth confirming.",
   src="coi-ladder-feeds.ts:223-237"),
 dict(n=4, id='C9', code='C9', label='Exempt income — participating interests', band='income', variant='both',
   mode_today='Editable — pre-filled', klass='',
   logic="Pre-filled from the Participation Exemption schedule (losses-exempted minus income-exempted). You can overtype it and your number wins (an amber 'schedule says X · Restore' strip shows).",
   feeds_in="Participation Exemption schedule (#12).",
   feeds_out="C24. Article 20(2)(b).",
   open="Cross-variant divergence: on the FZ side PE losses are ignored (RULING 125); the non-FZ C9 feed still adds PE losses back. See mapping decision C-2.",
   src="coi-ladder-feeds.ts:239-243"),
 dict(n=5, id='C10', code='C10', label='Exempt income — foreign permanent establishment', band='income', variant='both',
   mode_today='Editable — blank', klass='C',
   logic="Typed here as pure judgment; nothing pre-fills it and no schedule carries it today.",
   feeds_in="— (typed on this screen).",
   feeds_out="C24. Article 20(2)(b).",
   open="The Foreign-PE schedule totals exist but are NOT wired to this cell — see mapping decision C-2b (Q24).",
   src="coi-surface.ts:121 · ladder.ts:492"),
 dict(n=6, id='C12', code='C12', label='Qualifying Group Relief', band='income', variant='both',
   mode_today='Editable — pre-filled', klass='C',
   logic="Pre-filled from the Qualifying-Group feed (gain minus loss per row). You can overtype; your entry wins.",
   feeds_in="S151 Qualifying-Group transfer schedule.",
   feeds_out="C24. Article 20(2)(c).",
   open="Feed signs flagged 'ratify at staging'.",
   src="coi-feeds.ts:85-88,114-121"),
 dict(n=7, id='C13', code='C13', label='Business Restructuring Relief', band='income', variant='both',
   mode_today='Editable — pre-filled', klass='C',
   logic="Pre-filled from the Business-Restructuring relief and clawback rows, summed into one figure. You can overtype; your entry wins.",
   feeds_in="S160 relief + S161 clawback.",
   feeds_out="C24. Article 20(2)(c).",
   open="Feed signs flagged 'ratify at staging'.",
   src="coi-feeds.ts:92-101,122-135"),
 # BAND 2 — Add-backs
 dict(n=8, id='C15', code='C15', label='Not wholly & exclusively for business', band='addbacks', variant='both',
   mode_today='Read-only — from return', klass='B',
   logic="The amount classified on the return (Section F, Q6) as expenses not wholly and exclusively for business. Read-only add-back.",
   feeds_in="Return Section F, Q6.",
   feeds_out="C24. Article 20(2)(d).",
   open="",
   src="coi-ladder-feeds.ts:181-185"),
 dict(n=9, id='C16', code='C16', label='Capital nature', band='addbacks', variant='both',
   mode_today='Read-only — but NO source', klass='B',
   logic="Shipped as a read-only add-back — but no return field actually feeds it, so it renders 0 every time. The 'Reclassify upstream' link points at a schedule that does not capture a capital-nature figure.",
   feeds_in="None today.",
   feeds_out="C24. Article 20(2)(d).",
   open="OPEN (D-BRD11-1): the module header calls C16 a 'blank-but-summed line entered on this grid', but the build ships it read-only with no way to enter it. Where should C16 come from, and should it be editable here? This is exactly the kind of cell your annotation resolves.",
   src="coi-surface.ts:134-143 · coi-ladder-feeds.ts:37-39"),
 dict(n=10, id='C17', code='C17', label='Disallowed net interest (Art 30 cap)', band='addbacks', variant='both',
   mode_today='Editable — pre-filled', klass='A',
   logic="Pre-filled with the Interest Capping schedule's computed disallowed interest; you can override it.",
   feeds_in="Interest Capping schedule (Q10).",
   feeds_out="C24. Article 30.",
   open="",
   src="coi-surface.ts:144-153,462-464,499"),
 dict(n=11, id='C18', code='C18', label='Entertainment (50% disallowed)', band='addbacks', variant='both',
   mode_today='Read-only — from return', klass='B',
   logic="50% of the gross client-entertainment figure. The gross is entered only in Section C; the engine applies the halving. Read-only.",
   feeds_in="Section C, client entertainment (H9).",
   feeds_out="C24. Article 32.",
   open="Settled by RULING 97 / UAT-028 to the Section-C gross (the old Section-F cell is now a derived read-only display).",
   src="coi-ladder-feeds.ts:187-208 · ladder.ts:38-40"),
 dict(n=12, id='C19', code='C19', label='Expenditure related to exempt income', band='addbacks', variant='both',
   mode_today='Read-only — from return', klass='',
   logic="The amount on the return (Section F, Q4) for expenditure that produced exempt income. Read-only add-back.",
   feeds_in="Return Section F, Q4.",
   feeds_out="C24. Article 20(2)(d).",
   open="DISCLOSED FLIP (DEC-191): the owner's mockup showed C19 editable; the build ships it read-only (fed from its one entry home). Confirm the intended editability.",
   src="coi-ladder-feeds.ts:210-212"),
 dict(n=13, id='C20', code='C20', label='Other non-deductible expenditure', band='addbacks', variant='both',
   mode_today='Read-only — from return', klass='',
   logic="The other-non-deductible rows total, plus non-QPBE charitable donations, plus the Section-F 'other NDE' figure. QPBE donations are deductible upstream and excluded.",
   feeds_in="Other-NDE schedule rows + charitable (non-QPBE) + Section F Q7.",
   feeds_out="C24. Article 20(2)(d).",
   open="",
   src="coi-ladder-feeds.ts:118-126,214-217"),
 dict(n=14, id='C21', code='C21', label="Related-party arm's-length adjustment", band='addbacks', variant='both',
   mode_today='Editable — pre-filled', klass='',
   logic="Pre-filled with a one-way, taxpayer-adverse net: related-party upward minus downward, plus the connected-person disallowance. You can overtype; your entry wins.",
   feeds_in="S090 / S091 related-party schedules (+ per-transaction connected-person disallowance).",
   feeds_out="C24. Article 20(2)(e).",
   open="",
   src="coi-ladder-feeds.ts:128-135,245-249"),
 dict(n=15, id='C22', code='C22', label='Incentives / special reliefs', band='addbacks', variant='both',
   mode_today='Editable — blank · LESS row', klass='C',
   logic="Typed here as pure judgment. This is a 'Less' row — you type a positive number and the ladder subtracts it.",
   feeds_in="— (typed on this screen).",
   feeds_out="C24 (subtracted). Article 20(2)(h).",
   open="The QIP excluded-gain transitional relief was NOT routed here — it was directed at C23 instead (see mapping decision C-3). C22 stays manual.",
   src="coi-surface.ts:194 · ladder.ts:595-622"),
 dict(n=16, id='C23', code='C23', label='Ministerial-decision adjustment', band='addbacks', variant='both',
   mode_today='Editable — pre-filled', klass='C',
   logic="Pre-filled from the prior-period adjustment rows. You can overtype; your entry wins.",
   feeds_in="Prior-period adjustment rows (#107).",
   feeds_out="C24. Article 20(2)(i).",
   open="OPEN (Q-V2-061): the QIP excluded-gain transitional relief is the candidate to also feed C23 (entered negative). Not built — awaiting your ruling; the wire fails loudly until then. If it lands here, C23 becomes multi-source (see decisions C-3 / C-4).",
   src="coi-feeds.ts:104-107,136-142"),
 dict(n=17, id='C24', code='C24', label='Taxable Income before tax-loss relief', band='addbacks', variant='both',
   mode_today='Read-only — computed', klass='A',
   logic="The subtotal that closes the add-backs band: everything above added together, less C22. A 'Show working' drill-down is available.",
   feeds_in="All the lines above (C5, C6, C8–C23).",
   feeds_out="C25 and C26. Article 20.",
   open="",
   src="ladder.ts:604-623"),
 # BAND 3 — Deductions & reliefs
 dict(n=18, id='C25', code='C25', label='Tax-loss relief set-off', band='deductions', variant='both',
   mode_today='Editable — pre-filled · LESS row', klass='',
   logic="Pre-filled with the utilised row from the Tax Loss schedule. A 'Less' row (subtracted). Gated by the Art-39 continuity checkbox below: untick it and the set-off is forced to 0 and the whole balance carries forward.",
   feeds_in="Tax Loss schedule (utilised row) + the Art-39 continuity flag.",
   feeds_out="C26. Article 37.",
   open="",
   src="coi-surface.ts:197-206,465-467,506"),
 dict(n=19, id='C26', code='C26', label='Taxable Income subject to Corporate Tax', band='deductions', variant='both',
   mode_today='Read-only — computed', klass='A',
   logic="C24 minus C25.",
   feeds_in="C24, C25.",
   feeds_out="C27 / C28 (standard) or the C26Q / C26N split (Free-Zone). Article 20.",
   open="",
   src="ladder.ts:633-635"),
 # BAND 4 — Taxable income & tax
 dict(n=20, id='C26Q', code='C26Q', label='Qualifying Income subject to CT at 0%', band='tax', variant='FZ',
   mode_today='Read-only — computed (FZ split)', klass='A',
   logic="The qualifying-income base taxed at 0%. Renders ONLY on a Free-Zone filing that captured a 0%/9% split; fed from the Return's Free-Zone step.",
   feeds_in="Return Free-Zone step (the split's qualifying row).",
   feeds_out="C27. Article 3(2).",
   open="Renders only when a 0%/9% split was captured. The seeded Free-Zone demo (Gamma Free Zone) is a plain QFZP with no captured split, so this row does NOT appear on its Computation screen — the live shots therefore show the standard tax band; the FZ two-column source step is captured on the Return side.",
   src="coi-surface.ts:212-217 · ladder.ts:676-681"),
 dict(n=21, id='C26N', code='C26N', label='Other Income subject to CT at 9%', band='tax', variant='FZ',
   mode_today='Read-only — computed (FZ split)', klass='A',
   logic="The non-qualifying-income base run through the 375k / 9% band. FZ split path only.",
   feeds_in="Return Free-Zone step (the split's non-qualifying row).",
   feeds_out="C28. Article 3(2).",
   open="Same as C26Q: split path only. Did not render for the seeded plain-QFZP filing — see C26Q.",
   src="coi-surface.ts:218-223 · ladder.ts:301-307"),
 dict(n=22, id='C27', code='C27', label='Corporate Tax @ 0%', band='tax', variant='both',
   mode_today='Read-only — computed', klass='A',
   logic="The 0% band is always 0 (0% up to AED 375,000, never pro-rated).",
   feeds_in="C26 (or C26Q on a split).",
   feeds_out="C31. Article 3(1).",
   open="",
   src="ladder.ts:682,696-699"),
 dict(n=23, id='C28', code='C28', label='Corporate Tax @ 9% (over AED 375,000)', band='tax', variant='both',
   mode_today='Read-only — computed', klass='A',
   logic="Standard: 9% of income over AED 375,000. FZ split: 9% of the non-qualifying income. FZ de-minimis breach: 9% of the WHOLE income (the split is dropped). Plain QFZP: 0.",
   feeds_in="C26 / C26N.",
   feeds_out="C31. Article 3(1).",
   open="FZ de-minimis breach behaviour — see mapping decision on RULING 132.",
   src="ladder.ts:683-699"),
 dict(n=24, id='C29', code='C29', label='Less: Withholding tax credit', band='tax', variant='both',
   mode_today='Editable — blank · LESS · disabled at 0 CT', klass='C',
   logic="Typed here as judgment; a 'Less' row (subtracted). Editable ONLY if corporate tax before credits is above 0 — otherwise the field is disabled ('there is no corporate tax to relieve').",
   feeds_in="— (typed on this screen).",
   feeds_out="C31 (subtracted). Article 44.",
   open="Section-G 'Tax Credits (AED)' is captured on the return but NOT wired to this cell today — see mapping decision C-6.",
   src="computation-service.ts:330-339 · ladder.ts:711"),
 dict(n=25, id='C30', code='C30', label='Less: Foreign tax credit', band='tax', variant='both',
   mode_today='Editable — pre-filled · LESS · disabled at 0 CT', klass='',
   logic="Pre-filled with the Foreign Tax Credit schedule's total foreign liability (a positive figure the ladder subtracts). You can overtype. Same zero-CT disable as C29.",
   feeds_in="S080 Foreign Tax Credit schedule (#17).",
   feeds_out="C31 (subtracted). Article 47.",
   open="The seed is the RAW foreign liability with NO cap — an over-credit is possible. See mapping decision C-6 (apply a MIN cap?).",
   src="coi-ladder-feeds.ts:251-253"),
 dict(n=26, id='C31', code='C31', label='Corporate Tax Payable / (refundable)', band='tax', variant='both',
   mode_today='Read-only — computed (grand total)', klass='A',
   logic="Tax before credits, less (C29 + C30), floored at 0 — so a credit never turns into a refund.",
   feeds_in="C27, C28, C29, C30.",
   feeds_out="The extract stamp (CT payable). Article 3.",
   open="",
   src="ladder.ts:720-722"),
 # NON-LADDER cells on the same screen
 dict(n=27, id='fines', code='Fines flag', label='Fines & breach-of-contract treatment', band='other', variant='both',
   mode_today='Read-only display + link', klass='',
   logic="Fixed guidance: fines & penalties are non-deductible; damages / breach of contract are deductible. Read-only — to treat a fine as deductible you re-group the line upstream.",
   feeds_in="Return annexure-2 (fines & donations).",
   feeds_out="—",
   open="",
   src="computation-service.ts:77-81 · ComputationStage.tsx:299-312"),
 dict(n=28, id='art39', code='Art-39', label='Art-39 continuity maintained (checkbox)', band='other', variant='both',
   mode_today='Editable — checkbox', klass='',
   logic="Saved with the explicit Save. Untick it and the C25 tax-loss set-off is forced to 0 (the whole balance carries forward). Disabled when the whole surface is view-only.",
   feeds_in="Preparer.",
   feeds_out="Gates C25. SAL-165.",
   open="",
   src="ComputationStage.tsx:319-334 · coi-surface.ts:506"),
 dict(n=29, id='deminimis', code='De-minimis', label='De-minimis test: status · threshold', band='other', variant='FZ',
   mode_today='Read-only display (FZ only)', klass='',
   logic="The engine's verdict — not-tested / within-threshold / breached. Threshold = the LOWER of 5% of total revenue and AED 5,000,000. The test looks at non-qualifying REVENUE; a strictly-greater result breaches. Blank/zero total revenue → not-tested (never a breach from an untestable input).",
   feeds_in="Return Free-Zone step (total revenue + non-qualifying revenue).",
   feeds_out="The C28 rate branch (a breach runs the whole income at 9%). Cabinet Decision 100/2023, Art 18.",
   open="RULING 132 (Manthan, 2026-08-15): the de-minimis verdict decouples from the income split — a breach makes the return 'become a non-FZ return' (whole C26 at the standard band). Confirm the breach behaviour matches your reading.",
   src="ComputationStage.tsx:336-347 · ladder.ts:402-459,474-518"),
 dict(n=30, id='extract', code='Extract pins', label='Extract card — version-stamp pins', band='other', variant='both',
   mode_today='Read-only display', klass='',
   logic="The stamped pins on the Extract (PDF + Excel) card: rule-set version, financial-statement mapping version, FX basis, prior-year dataset, and the inherited tax position (B-prime). All read-only, stamped when an extract is minted.",
   feeds_in="Various (engine + config).",
   feeds_out="The extract record.",
   open="",
   src="ComputationStage.tsx:451-478 · computation-service.ts:276-306"),
]

# ── The auto-capture mapping proposal — the 28 Manthan questions, grouped ─────────────────────────
# Each decision: covers (which mapping-table rows) · line · today · candidate/hint · question · options · src
MAP_OPTS_DEST = ["Route it to the named computation cell", "Different cell (name it below)",
                 "Keep it capture-only (no computation destination)", "Discuss"]

MAP_DECISIONS = [
 # GROUP 1 — the 14 captured-but-unmapped lines (destination UNKNOWN)
 dict(n=1, id='U-23', group='unknown', covers='row 23',
   title='Equity-method profit — where should it land?', line="Section D · Equity-method profit (de_equity_method_profit)",
   today="Captured and stored, but feeds NO computation cell today.",
   hint="On the FZ variant the sibling row subtracts into the Free-Zone taxable-income default — the only hint at direction.",
   question="Where in the computation should equity-method profit land, or should it stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:447 · fz-split-rows.ts:192"),
 dict(n=2, id='U-24', group='unknown', covers='row 24',
   title='Equity-method loss — where should it land?', line="Section D · Equity-method loss (de_equity_method_loss)",
   today="Captured only; feeds no computation cell.",
   hint="FZ sibling ADDS into the Free-Zone default.",
   question="Where should equity-method loss land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:577 · fz-split-rows.ts:206"),
 dict(n=3, id='U-25', group='unknown', covers='row 25',
   title='Qualifying-Group transfer adjustment (#18)', line="Section D/E · Qualifying-Group transfer adjustment (de_qg_adjustment)",
   today="Manual placeholder — the aggregation logic is owed by Nexdigm (OW-25 / SAL-135).",
   hint="No FZ sibling precedent — this is Nexdigm-owed logic.",
   question="Which record stands for this line — OW-25 (Nexdigm-owed aggregation) or SAL-285 — and what is its computation destination?",
   options=["OW-25 stands", "SAL-285 stands", "Different (name it)", "Discuss"], src="manual-catalog.ts:453-459"),
 dict(n=4, id='U-26', group='unknown', covers='row 26',
   title='Unincorporated-partnership profits / losses', line="Section D · Unincorporated-partnership profits & losses (d_unincorp_profits / _losses)",
   today="Captured only; feeds no computation cell.",
   hint="FZ siblings: profits SUBTRACT, losses ADD into the Free-Zone default.",
   question="Where should the unincorporated-partnership profit and loss land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:584,591 · fz-split-rows.ts:217,232"),
 dict(n=5, id='U-27', group='unknown', covers='row 27',
   title='Unincorporated-PE disposal gains / losses', line="Section D · Unincorporated-PE disposal gains & losses (d_unincorp_pe_gains / _losses)",
   today="Captured only; feeds no computation cell.",
   hint="FZ siblings: gains SUBTRACT, losses ADD.",
   question="Where should these land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:598,605 · fz-split-rows.ts:244,257"),
 dict(n=6, id='U-28', group='unknown', covers='row 28',
   title='Prior-period gains / losses now realised (realisation basis)', line="Section D · Prior-period gains & losses now realised (d_prev_gains_realised / _losses_realised)",
   today="Captured only; feeds no computation cell. Possibly the C6 (unrealised) family.",
   hint="FZ siblings: prior gains realised ADD, losses realised SUBTRACT.",
   question="Where should these realised prior-period amounts land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:639,646 · fz-split-rows.ts:326,339"),
 dict(n=7, id='U-29', group='unknown', covers='row 29',
   title='Unrealised gains / losses (realisation-basis current)', line="Section D · Unrealised gains & losses, realisation basis (d_unrealised_gains / _losses)",
   today="Captured only. Same fields as the UGL question (see decision UGL-D5), on the realisation surface.",
   hint="FZ siblings: current unrealised gains SUBTRACT, losses ADD.",
   question="Where should the realisation-basis current unrealised amounts land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="fz-split-rows.ts:303,315"),
 dict(n=8, id='U-30', group='unknown', covers='row 30',
   title='Depreciation increase (realisation basis)', line="Section D · Depreciation increase, realisation basis (d_dep_increase_rb)",
   today="Captured only; feeds no computation cell.",
   hint="FZ sibling ADDS.",
   question="Where should the realisation-basis depreciation increase land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:653 · fz-split-rows.ts:351"),
 dict(n=9, id='U-31', group='unknown', covers='row 31',
   title='Other gain/loss increase / decrease (realisation)', line="Section D · Other G/L increase & decrease, realisation (d_other_gl_increase / _decrease)",
   today="Captured only; feeds no computation cell.",
   hint="FZ siblings: increase ADDS, decrease SUBTRACTS.",
   question="Where should these land, or stay capture-only?",
   options=MAP_OPTS_DEST, src="manual-catalog.ts:661,668 · fz-split-rows.ts:363,375"),
 dict(n=10, id='U-32', group='unknown', covers='row 32',
   title='Non-deductible pension contributions', line="Section F · Non-deductible pension contributions (f_pension_nondeductible)",
   today="Captured only; NOT read by any feed. Candidate: C20 (other non-deductible).",
   hint="FZ sibling ADDS into the Free-Zone default — confirms an add-back; likely C20.",
   question="Should non-deductible pension contributions feed C20 (other non-deductible), or another cell / stay capture-only?",
   options=["Yes — feed C20", "Different cell (name it)", "Keep capture-only", "Discuss"], src="manual-catalog.ts:1148 · fz-split-rows.ts:514"),
 dict(n=11, id='U-33', group='unknown', covers='row 33',
   title='Distributions to owners', line="Section F · Distributions to owners (f_owner_distributions)",
   today="Captured only. Candidate: C20.",
   hint="FZ sibling ADDS.",
   question="Should distributions to owners feed C20, or another cell / stay capture-only?",
   options=["Yes — feed C20", "Different cell (name it)", "Keep capture-only", "Discuss"], src="manual-catalog.ts:1168 · fz-split-rows.ts:549"),
 dict(n=12, id='U-34', group='unknown', covers='row 34',
   title='SIDLR-disallowed interest', line="Section F · Specific interest-deduction-limitation disallowed (f_sidlr_nondeductible)",
   today="Captured only. Possibly the C17 (interest) family, or a separate line.",
   hint="FZ sibling ADDS.",
   question="Where should the SIDLR-disallowed interest land — with C17, a new line, or capture-only?",
   options=["With C17 (interest)", "A separate computation line", "Keep capture-only", "Discuss"], src="manual-catalog.ts:1195 · fz-split-rows.ts:603"),
 dict(n=13, id='U-35', group='unknown', covers='row 35',
   title='Prior-period non-ALP related-party gains / losses now taxable', line="Section F · Prior-period non-arm's-length RP gains & losses (f_rpt_prev_gains / _losses)",
   today="Captured only. Possibly the C21 (related-party) or C23 family.",
   hint="FZ siblings: gains ADD, losses SUBTRACT.",
   question="Where should these prior-period related-party amounts land, or stay capture-only?",
   options=["With C21 (related-party)", "With C23 (ministerial)", "Different cell (name it)", "Keep capture-only", "Discuss"], src="manual-catalog.ts:1218,1226 · fz-split-rows.ts:634,645"),
 dict(n=14, id='U-36', group='unknown', covers='row 36',
   title='International shipping / aircraft income & expenditure', line="Section E · International shipping/aircraft income & expenditure (fz_aircraft_income_11b / _expenditure_11c)",
   today="Captured only; test-pinned to 'never reach a computation'. But the FZ two-column rows feed the SAME figure into the Free-Zone default — a double-surface.",
   hint="Double-surface: the E-block capture and the FZ two-column both hold this figure.",
   question="Reconcile the E-block capture against the FZ two-column: which surface owns international shipping/aircraft income & expenditure, and where should it land?",
   options=["FZ two-column owns it", "E-block owns it", "Different (explain below)", "Discuss"], src="assembly.test.ts:785-808 · fz-split-rows.ts:472-495"),

 # GROUP 2 — the 6 collisions
 dict(n=15, id='C-1', group='collision', covers='row 11',
   title='C-1 · Connected-person adjustment: preparer-owned (RULING 124)', line="Section F13b · Payments to Connected Persons not at market value (f_cp_adjustments)",
   today="Preparer-owned, pre-filled (per-transaction engine value, you can override); the CP-schedule total is permanently gated. C21 already consumes the engine's connected-person disallowance.",
   hint="Auto-mapping the CP-schedule total into a cell would REVERSE RULING 124 and double-count against C21.",
   question="Keep the connected-person line exactly as built (preparer-owned, schedule total gated) — or overturn RULING 124 and auto-capture the schedule total?",
   options=["Keep as built (RULING 124 stands)", "Overturn RULING 124 — auto-capture the schedule total", "Discuss"], src="cp-schedule.ts:403-408 · coi-ladder-feeds.ts:128-135"),
 dict(n=16, id='C-2', group='collision', covers='rows 3, 4, 22',
   title='C-2 · Participation-exemption losses: FZ ignores them, non-FZ adds them back', line="Participation Exemption schedule (#12) → C9",
   today="On the FZ side PE losses are correctly ignored (RULING 125). On the non-FZ side the C9 feed still adds PE losses back (losses minus income). The two variants disagree.",
   hint="RULING 125 is currently FZ-scoped.",
   question="Does RULING 125 (participation-exemption losses ignored; income subtracts) extend to the NON-FZ C9 feed, or is it Free-Zone only?",
   options=["Extend to non-FZ (losses = 0 there too)", "Keep FZ-only (non-FZ keeps adding losses back)", "Discuss"], src="coi-ladder-feeds.ts:239-243"),
 dict(n=17, id='C-3', group='collision', covers='rows 19, 20, 21',
   title='C-3 · Transitional excluded gains → C23 (negative)?', line="QIP #5 / intangible S180 #8 / financial-asset FA-FL #9-#10 — excluded-gain totals",
   today="All four disposal-schedule excluded-gain totals are fail-loud gated (nothing reaches the computation). The in-code candidate is C23, entered negative — C22 was rejected (it is enumerated exempt income, not a transitional adjustment).",
   hint="One ruling can cover all four disposal schedules. Note: the engine-side gate comment names C24 while the returns side names C23 — reconcile at ratification.",
   question="Confirm the QIP / intangible / financial-asset excluded gains should feed C23 (negative) for all four schedules — and confirm C22 is not the home.",
   options=["Yes — C23 (negative), all four", "A different cell (name it)", "Keep gated for now", "Discuss"], src="coi-feeds.ts:159-168,216-218 · excluded-gains.ts:22"),
 dict(n=18, id='C-4', group='collision', covers='row 16',
   title='C-4 · Prior-period C23 becomes multi-source', line="Prior-period adjustments (#107) → C23 (live)",
   today="C23 is live from the prior-period rows (RULING 36). If QIP / intangible / financial-asset gains ALSO route to C23 (decision C-3), the cell becomes multi-source and additive.",
   hint="Also open: whether the prior-period total should ALSO land on a Section-F return line (still 'ratify at staging').",
   question="Confirm C23 may carry multiple sources additively (prior-period + transitional gains), and rule whether the prior-period total also lands on an F-line.",
   options=["Yes — multi-source C23 is fine; no F-line", "Multi-source + also an F-line", "Keep prior-period only on C23", "Discuss"], src="coi-feeds.ts:104-107"),
 dict(n=19, id='C-5', group='collision', covers='rows 37, 38',
   title='C-5 · Tax-loss transfers in / out (S110 / S111) are unwired', line="S110 losses claimed FROM others / S111 losses transferred TO others",
   today="All three destinations (the G-2b display and the two engine tax-loss feeds) are declared but NOT wired — the amounts display but reach no computation.",
   hint="Needs over-transfer handling too (own-losses-first, the recipient's 75% cap).",
   question="Authorise wiring the transfer-in total to G-2b + the engine 'losses claimed' feed, and the transfer-out total to the 'losses transferred' feed?",
   options=["Yes — wire both, with over-transfer guards", "Only one direction (say which)", "Not for V1", "Discuss"], src="tax-loss-transfer.ts:38-46"),
 dict(n=20, id='C-6', group='collision', covers='rows 17, 41',
   title='C-6 · Tax-credit cap (C29 / C30)', line="Foreign tax credit (S080) → C30 · Section-G tax credits → C29",
   today="C30 seeds the RAW foreign liability with no cap; C31 only floors at zero — so an over-credit is possible. The Section-G 'Tax Credits (AED)' is captured but not wired to C29.",
   hint="Candidate rule: MIN(foreign liability, UAE CT on that income).",
   question="Rule the credit formula — apply a MIN cap to the foreign tax credit — and wire Section-G tax credits to C29?",
   options=["Yes — MIN cap on C30 + wire C29", "MIN cap only", "Wire C29 only", "Leave as built", "Discuss"], src="coi-ladder-feeds.ts:251-253 · ladder.ts:721 · assembly.ts:2843-2844"),

 # GROUP 3 — FZ / non-FZ divergence, FPE, UGL, and OQ-1
 dict(n=21, id='C-2b', group='divergence', covers='row 39',
   title='C-2b · Foreign-PE result → C10 (mirror C9)?', line="Foreign-PE schedules (#104 prior / #105 current / #106 ineligible) → C10",
   today="The C10 seed is unruled — the Foreign-PE totals are declared display-only and NOT wired to the computation.",
   hint="Mirroring the C9 arrangement is what open Q24 asks; and whether FPE losses follow the RULING-125 zero carve-out.",
   question="Rule the C10 seed: should the Foreign-PE income total feed C10 (mirroring C9), and do FPE losses follow the losses-ignored carve-out?",
   options=["Yes — feed C10; losses ignored", "Feed C10; losses included", "Keep C10 manual", "Discuss"], src="fpe-trio.ts:217-228"),
 dict(n=22, id='UGL-D5', group='divergence', covers='row 18',
   title='Unrealised gains/losses (D5, schedule #7) — which cell, without double-counting?', line="Section D5 · Unrealised gains & losses (UGL schedule #7)",
   today="Feeds a Section-D display cell only; NOT in the computation. The obvious home is C6 — but C6 is ALREADY fed by schedule #6, so routing #7 there too would double the unrealised line.",
   hint="Two schedules (#6 and #7) touch the same C6 concept.",
   question="Should the UGL #7 total auto-capture into a computation cell — and if so which, given C6 is already taken by schedule #6?",
   options=["Route #7 to C6 (and reconcile the #6 overlap)", "A different cell (name it)", "Keep capture-only", "Discuss"], src="assembly.ts:2922-2925 · ugl-schedule.ts:45-52"),
 dict(n=23, id='OQ-1', group='divergence', covers='FZ sign map',
   title='OQ-1 · The Free-Zone two-column sign map is unratified', line="Free-Zone no303 'Taxable Income before loss adjustments' — every two-column row's contribution sign",
   today="On the FZ variant every two-column money row already contributes to a system-computed default with an editable override — the pattern RULING 145 wants, applied wholesale. But the contribution sign map (which rows add vs subtract) is build-current and client-UNCONFIRMED.",
   hint="This is the FZ side of the whole mapping — substantially built; only the signs want a ratify.",
   question="Ratify the Free-Zone two-column contribution sign map (which rows add, which subtract into the taxable-income default) as built?",
   options=["Ratify as built", "Ratify with changes (list below)", "Discuss"], src="fz-split-rows.ts:56"),
]

MAP_GROUPS = [
 ('unknown', 'The 14 captured-but-unmapped lines', "Money the return captures today that reaches NO computation cell. Each needs a destination ruling before anything is wired — a guessed cell is a fabricated destination. The Free-Zone sibling's direction (add / subtract) is the only precedent, and it is cited."),
 ('collision', 'The 6 collisions', "Auto-mapping these would require you to overturn or confirm an existing ruling, or would double-count against a cell that already consumes the figure. Each is framed as a keep-or-change decision."),
 ('divergence', 'PE / FPE loss divergence, UGL, and the FZ sign map (OQ-1)', "Where the two variants disagree today (participation-exemption and foreign-PE losses), the one double-count risk (UGL), and the one Free-Zone ratification that unblocks the whole FZ side."),
]

# ── What's already correct (the "solid" list) ────────────────────────────────────────────────────
SOLID = [
 "**The engine is the only calculator.** This screen does no arithmetic of its own — it re-runs the same engine ladder over the declared return, so the screen, the PDF extract and the Excel extract can never disagree.",
 "**C5 accounting income** is fed from the financial-statement mapping and rounded once to whole AED — ruled and fed. *(ladder.ts:556-557)*",
 "**C8 dividends** correctly passes exempt income as a negative, owned by the UAE Dividend schedule. *(coi-ladder-feeds.ts:223-237)*",
 "**C15 not-wholly-exclusive**, **C19 exempt-income expenditure**, **C20 other non-deductible** are fed from their single return homes — no double-keying. *(coi-ladder-feeds.ts:181-217)*",
 "**C17 interest cap** is pre-filled from the Interest Capping schedule's computed disallowed interest and overridable. *(coi-surface.ts:462-464)*",
 "**C18 entertainment** applies the 50% halving in the engine from a single Section-C gross — RULING 97 / UAT-028 settled, the old Section-F cell is now a derived read-only display. *(coi-ladder-feeds.ts:187-208)*",
 "**C21 related-party** consumes a one-way, taxpayer-adverse net (upward − downward + connected-person) — the direction matches the portal's own popup. *(coi-ladder-feeds.ts:128-135)*",
 "**C24 / C26 / C27 / C28 / C31** subtotals and rate bands are code-traceable to the ladder; the 0% band is always 0, the 9% band is 9% over AED 375,000, and C31 is floored so a credit never refunds. *(ladder.ts:604-722)*",
 "**C25 tax-loss set-off** applies the utilised row and is correctly gated by the Art-39 continuity checkbox (untick → 0, whole balance carries forward). *(coi-surface.ts:465-467,506)*",
 "**The rate path is driven by Section A + the Free-Zone details only** — no computation-page input can flip the rate (RULING 65; the old QFZP/split checkboxes were removed). *(computation-service.ts:414-420)*",
 "**C29 / C30 credits disable when there is no corporate tax to relieve** — you can't record a credit against zero tax. *(computation-service.ts:330-339)*",
 "**Fail-loud gates.** Where the engine cannot compute honestly (participation exemption, qualifying-group aggregation, the QIP excluded-gain wire) it REFUSES rather than guess a number. *(ladder.ts:520-538 · coi-feeds.ts:216-218)*",
 "**The whole Free-Zone two-column mechanism** already contributes every money row to a system-computed taxable-income default with an editable override — the seed-editable pattern, applied wholesale. Only the sign map wants a ratify (OQ-1). *(fz-split-rows.ts)*",
]

# ── Glossary (engineering terms, explained once) ─────────────────────────────────────────────────
GLOSSARY = [
 ("Cell / C-code", "One line on the Computation screen (C5 … C31). The letter-number is the code the return and the engine share."),
 ("Class A / B / C", "The screen's legend. A = read-only, computed by the engine. B = classify-then-compute (a human classifies the underlying lines upstream, the engine applies the rule). C = pure judgment, human-entered, never system-computed."),
 ("Seed / seeded / pre-filled", "A cell arrives pre-filled from its owning schedule but you may overtype it — your number always wins, and an amber 'schedule says X · Restore' strip appears. Restoring drops your entry so the schedule governs again."),
 ("Feed / fed line", "A read-only cell whose number lives in exactly ONE upstream place; you change it only via the 'Reclassify upstream' link, never by typing here — so the return and the computation can never disagree."),
 ("Carrier", "The persisted return field or schedule column a feed reads from. 'No carrier' (C16) means the cell is declared fed but nothing actually fills it."),
 ("Gate / fail-loud", "A seam the engine refuses rather than guess: it throws an error instead of inventing a number, until the rule is ruled."),
 ("'Less' row", "C22, C25, C29, C30 — you type a positive number and the ladder SUBTRACTS it. A leading minus on screen is display-only."),
 ("Extract / stamp", "Minting a versioned, immutable copy of the computation (engine version, timestamp, CT payable). Any edit after an extract mints a new version."),
 ("De-minimis", "The Free-Zone threshold test: non-qualifying revenue must stay at or below the LOWER of (5% of total revenue, AED 5m); a breach loses Free-Zone status for this year and the next four."),
 ("no303 / two-column default", "On a Free-Zone filing, the system-computed 'Taxable Income before loss adjustments' that every two-column money row contributes to, with an editable override (RULING 34)."),
 ("Ruling / RULING nnn · Q-nnn · OQ / SAL / DEC", "A recorded decision (or open question) in the project's ruling ledger. Cited so engineers can trace each claim; you can ignore the codes."),
]

# ── The left index (mirrors the computation screen order) ────────────────────────────────────────
SECTIONS_GUIDE = [
 ('start', 'Start here', 'How to read this, and the three questions asked on every cell.'),
 ('cells', 'The 30 cells', 'The Computation screen, top to bottom, grouped as the screen groups it. Answer each in place.'),
 ('mapping', 'Mapping proposal (28)', 'The auto-capture questions: 14 unmapped lines, 6 collisions, the PE/FPE divergence, and the Free-Zone sign map.'),
 ('solid', "What's already correct", "The cells whose logic is ruled and fed — so the picture is balanced."),
 ('replica', 'Full replica table', 'Reference: every cell with its logic, feeds and file:line. You do not need to read this.'),
 ('glossary', 'Glossary', 'The engineering terms, in plain words — read once.'),
 ('sources', 'Sources & method', 'The two source documents and how this page was built.'),
]

# ── Screenshot captions (builder attaches only files that exist) ─────────────────────────────────
IMG_CAPTIONS = {
 'nonfz/comp-full.png': 'Computation screen (non-FZ) — full page',
 'nonfz/comp-band1.png': 'Band 1 — Income & accounting base (C5–C13)',
 'nonfz/comp-band2.png': 'Band 2 — Add-backs (C15–C24)',
 'nonfz/comp-band3.png': 'Band 3 — Deductions & reliefs (C25–C26)',
 'nonfz/comp-band4.png': 'Band 4 — Taxable income & tax (C27–C31)',
 'nonfz/comp-nonladder.png': 'Fines flag + Art-39 continuity checkbox',
 'nonfz/comp-extract.png': 'Extract (PDF + Excel) version-stamp card',
 'nonfz/return-D.png': 'Return — Section D (accounting adjustments): the "where it comes from" side',
 'nonfz/return-E.png': 'Return — Elections / reliefs step (nearest to Section E)',
 'nonfz/return-F.png': 'Return — Section F (other adjustments)',
 'nonfz/return-G.png': 'Return — Section G (tax losses & credits)',
 'fz/comp-full.png': 'Computation screen (Free-Zone) — full page',
 'fz/comp-deminimis.png': 'De-minimis test line (Free-Zone)',
 'fz/comp-band4.png': 'Band 4 — Taxable income & tax (Free-Zone)',
 'fz/comp-nonladder.png': 'Free-Zone — Art-39 continuity + de-minimis area',
 'fz/return-fz-twocolumn.png': 'Return — Free-Zone two-column (0% / 9%) adjustment step',
 'fz/return-fz-taxliability.png': 'Return — Free-Zone tax liability & credits step',
}
# Which crop each band shows (a cell shows its band crop + the full-page shot).
BAND_IMG = {
 'income': ['nonfz/comp-band1.png'], 'addbacks': ['nonfz/comp-band2.png'],
 'deductions': ['nonfz/comp-band3.png'], 'tax': ['nonfz/comp-band4.png'],
 'other': ['nonfz/comp-nonladder.png', 'nonfz/comp-extract.png'],
}
FZ_CELL_IMG = {'C26Q': ['fz/comp-full.png', 'fz/return-fz-twocolumn.png'],
               'C26N': ['fz/comp-full.png', 'fz/return-fz-twocolumn.png'],
               'deminimis': ['fz/return-fz-twocolumn.png']}
